== MW210V_Lathe_Gears

Calculate / determine gear sets for feedrates and thread cutting on the MW210V and similar lathes. Inspired by the program by Matthias Wandel <https://github.com/Matthias-Wandel/lathe-thread-gears>, but apart from perhaps a handful lines of code, completely different.

There's more info for this code here on my website <http://hankjr.ca/lathes/>.

The gear tables on these lathes aren't great. Missing feedrates, inaccurate rates, it's pretty bad.

This Python program will check all possible combinations that are possible with the collection of gears you have available, and gives you the nearset approximations of the feedrates you specify.

Results are written to stdout, as well as a logfile 'gears_result'. Data (gears available, feedrates desired, lathe specifics &c.) is entered into a config/data input file 'lathe_data' that is read at startup.

The output in 'gears_result' is formatted like the gear table on the lathe and looks like:

....
Lathe feed/thread cutting gear populations for MW210V lathe.

Available gears: [24, 30, 40, 48, 50, 52, 60, 60, 66, 70, 72, 75]
Target feedrates: [6, 7, 8, 9, 10, 11, 14, 19, 20, 22, 24, 28, 32, 40, 44]

             72    H
   5.98714   30   75  Error: -0.214%
              H   66
   6 TPI -----------
             30    H
   6.04762   50   75  Error: 0.794%
              H   40

             75    H
   6.99796   72   70  Error: -0.029%
              H   30
   7 TPI -----------
             60    H
   7.07571   24   40  Error: 1.082%
              H   52
   .
   .
And so on...
   .
   .
....

Running 'pyton3 lathe_gears.py -h' gets you:

....
usage: lathe_gears.py [-h] [-g 84,72,60 ...] [-p 28,20,19 ...] [-u {mm,tpi}]
                      [-c 60,40,H,80,H,70 [target-pitch ...]] [-i file_name]
                      [-e [file_name]] [-o file_name] [-f {list,layout}]

Determine gear sets for feed-rates on a lathe, written with the MW210V in
mind.

options:
  -h, --help            show this help message and exit
  -g, --gears 84,72,60 ...
                        Comma separated list of available gears.
  -p, --pitches 28,20,19 ...
                        Comma separated list of feedrate(s) of interest.
  -u, --unit {mm,tpi}   Pitch unit.
  -c, --check 60,40,H,80,H,70 [target-pitch ...]
                        Check a gear set--given as a comma separated list of
                        6(!) gear positions A,B,C,D,E,F--for fit and resulting
                        pitch. Target-pitch is optional, if specified, an
                        error percentage is also calculated; you _must_ use
                        'H' for empty gear positions as per the example.
  -i, --input file_name
                        Data file name when not using the default
                        'lathe_data'; provide full path if it's not located in
                        the program directory.
  -e, --example [file_name]
                        Create an example lathe data file and exit. The file
                        name is optional and defaults to 'gear_data_example'.
  -o, --output file_name
                        Non-default output file name; defaults are set in the
                        data file.
  -f, --format {list,layout}
                        Output format, 'list' lists ALL working sets in a
                        simple format, 'layout' only gives the best* sets in a
                        pretty layout. (*see README)
....
