== MW210V_Lathe_Gears

Calculate / determine gear sets for feedrates and thread cutting on the MW210V and similar lathes. Inspired by the program by Matthias Wandel <https://github.com/Matthias-Wandel/lathe-thread-gears>, but apart from a handful lines of code, completely different.

The gear tables on these lathes aren't great. Missing feedrates, inaccurate rates, it's pretty bad.

This Python program will check all possible combinations that are possible with the collection of gears you have available, and gives you the nearset approximations of the feedrates you specify.

Results are written to stdout, as well as a logfile. Data (gears available, feedrates desired, lathe specifics &c.) can be entered into the code, entered on the command line, or saved in a config file that is read at startup.

The 'lathe_data_example' is an example of the config file.

The 'lathe_gears_result' is an example of the output file, which looks like:

....
Lathe feed/thread cutting gear populations for MW210V lathe.

Available gears: [24, 30, 40, 48, 50, 52, 60, 60, 66, 70, 72, 75].
Target feedrates: [7, 8, 9, 10, 11, 14, 19, 20, 22, 24, 28, 32, 40, 44]

             72    H
   5.98714   30   75  Error: -0.214%
              H   66
   6 TPI -----------
             30    H
   6.04762   50   75  Error: 0.794%
              H   40

             75    H
   6.99796   72   70  Error: -0.029%
              H   30
   7 TPI -----------
             60    H
   7.07571   24   40  Error: 1.082%
              H   52

....

Running 'pyton3 lathe_gears.py -h' gets you:

....
usage: lathe_gears.py [-h] [-g GEARS] [-p PITCHES] [-u {mm,tpi}] [-c CHECK]
                      [-f [FILE ...]] [-e [EXAMPLE ...]] [-o OUTPUT]
Determine gear sets for feed-rates on a lathe, written with the MW210V in
mind.
options:
  -h, --help            show this help message and exit  
  -g, --gears GEARS     Comma separated list of available gears, e.g.
                        -g=84,72,60,42
  -p, --pitches PITCHES
                        Comma separated list of feedrate(s) of interest, e.g.
                        -p=8,12,16,24
  -u, --unit {mm,tpi}   Pitch unit, mm is the default.
  -c, --check CHECK     Check a gear set, given as a comma separated list of
                        6(!) gear positions A B C D E F, e.g.
                        -c=60,40,H,80,H,56 ('H' for empty positions) for fit
                        and resulting pitch.
  -f, --file [FILE ...]
                        Use data from file, provide full path if it's not
                        located in the program directory, default is local
                        file 'lathe_data'.
  -e, --example [EXAMPLE ...]
                        Create an example lathe data file and exit, file name
                        is optional.
  -o, --output OUTPUT   Output file name, default is 'lathe_gears_result'.
....
